# TCL File Generated by Component Editor 18.1
# Sat Nov 27 15:28:47 EST 2021
# DO NOT MODIFY


# 
# VGA_text_mode_controller "VGA_text_mode_controller" v1.0
# Byron Lathi 2021.11.27.15:28:47
# Memory Mapped vga text mode controller.
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module VGA_text_mode_controller
# 
set_module_property DESCRIPTION "Memory Mapped vga text mode controller."
set_module_property NAME VGA_text_mode_controller
set_module_property VERSION 1.1	
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ECE385 Custom IPs"
set_module_property AUTHOR "Byron Lathi"
set_module_property DISPLAY_NAME VGA_text_mode_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property VALIDATION_CALLBACK validate


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_text_avl_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file VGA_controller.sv SYSTEM_VERILOG PATH ip/vga/VGA_controller.sv
add_fileset_file vga_text_avl_interface.sv SYSTEM_VERILOG PATH ip/vga/vga_text_avl_interface.sv TOP_LEVEL_FILE
add_fileset_file note.sv SYSTEM_VERILOG PATH ip/vga/note.sv
add_fileset_file note_controller.sv SYSTEM_VERILOG PATH ip/vga/note_controller.sv
add_fileset_file note_rom.sv SYSTEM_VERILOG PATH ip/vga/note_rom.sv
add_fileset_file fret.sv SYSTEM_VERILOG PATH ip/vga/fret.sv
add_fileset_file fret_rom.sv SYSTEM_VERILOG PATH ip/vga/fret_rom.sv


# 
# parameters
# 
add_parameter count INTEGER 3 "Number of note sprites"
set_parameter_property count DEFAULT_VALUE 3
set_parameter_property count DISPLAY_NAME count
set_parameter_property count TYPE INTEGER
set_parameter_property count UNITS None
set_parameter_property count ALLOWED_RANGES -2147483648:2147483647
set_parameter_property count DESCRIPTION "Number of note sprites"
set_parameter_property count HDL_PARAMETER true
add_parameter width INTEGER 2 "count <= (2^width)-1"
set_parameter_property width DEFAULT_VALUE 2
set_parameter_property width DISPLAY_NAME width
set_parameter_property width TYPE INTEGER
set_parameter_property width UNITS None
set_parameter_property width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property width DESCRIPTION "count <= (2^width)-1"
set_parameter_property width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLK clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset RESET reset Input 1


# 
# connection point AVL
# 
add_interface AVL avalon end
set_interface_property AVL addressUnits WORDS
set_interface_property AVL associatedClock clock
set_interface_property AVL associatedReset reset
set_interface_property AVL bitsPerSymbol 8
set_interface_property AVL burstOnBurstBoundariesOnly false
set_interface_property AVL burstcountUnits WORDS
set_interface_property AVL explicitAddressSpan 0
set_interface_property AVL holdTime 0
set_interface_property AVL linewrapBursts false
set_interface_property AVL maximumPendingReadTransactions 0
set_interface_property AVL maximumPendingWriteTransactions 0
set_interface_property AVL readLatency 0
set_interface_property AVL readWaitTime 1
set_interface_property AVL setupTime 0
set_interface_property AVL timingUnits Cycles
set_interface_property AVL writeWaitTime 0
set_interface_property AVL ENABLED true
set_interface_property AVL EXPORT_OF ""
set_interface_property AVL PORT_NAME_MAP ""
set_interface_property AVL CMSIS_SVD_VARIABLES ""
set_interface_property AVL SVD_ADDRESS_GROUP ""

add_interface_port AVL AVL_CS chipselect Input 1
add_interface_port AVL AVL_READ read Input 1
add_interface_port AVL AVL_READDATA readdata Output 32
add_interface_port AVL AVL_WRITE write Input 1
add_interface_port AVL AVL_WRITEDATA writedata Input 32
add_interface_port AVL AVL_ADDR address Input width
add_interface_port AVL AVL_BYTE_EN byteenable Input 4
set_interface_assignment AVL embeddedsw.configuration.isFlash 0
set_interface_assignment AVL embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment AVL embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment AVL embeddedsw.configuration.isPrintableDevice 0


# 
# connection point vga
# 
add_interface vga conduit end
set_interface_property vga associatedClock clock
set_interface_property vga associatedReset ""
set_interface_property vga ENABLED true
set_interface_property vga EXPORT_OF ""
set_interface_property vga PORT_NAME_MAP ""
set_interface_property vga CMSIS_SVD_VARIABLES ""
set_interface_property vga SVD_ADDRESS_GROUP ""

add_interface_port vga red red Output 4
add_interface_port vga green green Output 4
add_interface_port vga blue blue Output 4
add_interface_port vga hs hs Output 1
add_interface_port vga vs vs Output 1

proc validate {} {
	set count [ get_parameter_value count ]
	set_module_assignment embeddedsw.CMacro.NOTE_COUNT "$count"
	
	set width [ get_parameter_value width ]
	set_module_assignment embeddedsw.CMacro.ADDR_WIDTH "$width"
}
