# TCL File Generated by Component Editor 18.1
# Fri Oct 29 14:14:00 CDT 2021
# DO NOT MODIFY


# 
# vga_text_controller "vga_text_controller" v1.0
# Shin and Dimov 2021.10.29.14:14:00
# Lab 7 IP for VGA text
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_text_controller
# 
set_module_property DESCRIPTION "Lab 7 IP for VGA text"
set_module_property NAME vga_text_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ECE 385 Custom IPs"
set_module_property AUTHOR "Shin and Dimov"
set_module_property DISPLAY_NAME vga_text_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_text_avl_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_text_avl_interface.sv SYSTEM_VERILOG PATH lab7soc/synthesis/submodules/vga_text_avl_interface.sv
add_fileset_file font_rom.sv SYSTEM_VERILOG PATH lab7soc/synthesis/submodules/font_rom.sv
add_fileset_file VGA_controller.sv SYSTEM_VERILOG PATH lab7soc/synthesis/submodules/VGA_controller.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL vga_text_avl_interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_text_avl_interface.sv SYSTEM_VERILOG PATH lab7soc/synthesis/submodules/vga_text_avl_interface.sv
add_fileset_file font_rom.sv SYSTEM_VERILOG PATH lab7soc/synthesis/submodules/font_rom.sv
add_fileset_file VGA_controller.sv SYSTEM_VERILOG PATH lab7soc/synthesis/submodules/VGA_controller.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock CLK
set_interface_property avalon_slave associatedReset RESET
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave AVL_ADDR address Input 10
add_interface_port avalon_slave AVL_BYTE_EN byteenable Input 4
add_interface_port avalon_slave AVL_READDATA readdata Output 32
add_interface_port avalon_slave AVL_WRITEDATA writedata Input 32
add_interface_port avalon_slave AVL_CS chipselect Input 1
add_interface_port avalon_slave AVL_READ read Input 1
add_interface_port avalon_slave AVL_WRITE write Input 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point vga_port
# 
add_interface vga_port conduit end
set_interface_property vga_port associatedClock CLK
set_interface_property vga_port associatedReset ""
set_interface_property vga_port ENABLED true
set_interface_property vga_port EXPORT_OF ""
set_interface_property vga_port PORT_NAME_MAP ""
set_interface_property vga_port CMSIS_SVD_VARIABLES ""
set_interface_property vga_port SVD_ADDRESS_GROUP ""

add_interface_port vga_port red red Output 4
add_interface_port vga_port green green Output 4
add_interface_port vga_port blue blue Output 4
add_interface_port vga_port hs hs Output 1
add_interface_port vga_port vs vs Output 1

